FROM public.ecr.aws/lambda/java:11
MAINTAINER gabriel@ikonintegration.com

# Copy function code and runtime dependencies from Maven layout
COPY target/classes ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "$ENTRYPOINT::$ENTRYPOINT_FUNC" ]