FROM ghcr.io/hybridless/node:18-alpine

# Copy files
COPY /usr/src/app/ /usr/src/app/

# Set the working directory
WORKDIR /usr/src/app

# Run the specified command within the container.
ENTRYPOINT node -e "import('./$ENTRYPOINT').then( m => m['$ENTRYPOINT_FUNC']() )"