FROM ghcr.io/hybridless/go:1.21

# Set the working directory inside the container
WORKDIR /app

# Expose
EXPOSE $PORT

# Copy files
COPY /app/ /app/

# Command to run the executable
CMD ["./$ENTRYPOINT"]