FROM ghcr.io/hybridless/golang:1.21

# Set the working directory inside the container
WORKDIR /app

# Expose
EXPOSE $PORT

# Copy files
COPY /app/ /app/
#
RUN chmod +x go.sh
# Command to run the executable
ENTRYPOINT ["./go.sh"]