FROM public.ecr.aws/lambda/nodejs:12
MAINTAINER gabriel@ikonintegration.com

# Copy function code
COPY /usr/src/app/ ${LAMBDA_TASK_ROOT}

# 
ENTRYPOINT /lambda-entrypoint.sh "$ENTRYPOINT.$ENTRYPOINT_FUNC"