FROM public.ecr.aws/lambda/java:8al12

# Copy function code and runtime dependencies from Maven layout
COPY target/classes ${LAMBDA_TASK_ROOT}
COPY target/dependency/* ${LAMBDA_TASK_ROOT}/lib/
COPY hybridless-entrypoint.sh ${LAMBDA_TASK_ROOT}/

# 
ENTRYPOINT ["hybridless-entrypoint.sh"]